version: '3'
services:
  client:
    build:
      context: .
    container_name: crytpoquery-client-dev
    environment:
      NODE_ENV: 'development'
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4200:4200
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: npm start
